---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-12.04
    run_list:
      - recipe[apt]
  - name: centos-6.4
    run_list:
      - recipe[yum]

suites:
  - name: default
    run_list:
      - recipe[sabnzbd::default]
    attributes:
  - name: runit
    run_list:
      - recipe[sabnzbd::default]
    attributes:
      sabnzbd:
        init_style: runit
